#! /bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 10
bspc config top_padding          0
bspc config border_width         1.5
bspc config window_gap          14
bspc config split_ratio          1.51
bspc config focused_border_color "#3DE1CC"
bspc config presel_feedback_color "#1ABB9B"
bspc config borderless_monocle        false
bspc config gapless_monocle           false
bspc config single_monocle            true
bspc config remove_disabled_monitors  true
bspc config remove_unplugged_monitors true
bspc config focus_follows_pointer     true ## this lets the cursor focus a window

bspc rule -a Emacs state=tiled

sxhkd &
mpd &
picom &
dunst &
xset r rate 300 50 &
unclutter &
polybar bar &
/home/goku/code/bash/bg > /dev/null &

doas /dev/sda3 ~/Downloads

pidof -s runit &&
	! pidof -s pulseaudio >/dev/null 2>&1 &&
	setsid -f pulseaudio --start --exit-idle-time=-1 >/dev/null 2>&1

emacs --daemon &
