#! /bin/sh
bspc monitor -d I II III IV V VI VII
bspc config border_width         0
bspc config window_gap          6
bsp config presel_feedback_color "#ffffff" 
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config top_padding 20

#bspc config focused_border_color "#A27ED5"
#bspc config normal_border_color "#4A4D64"
bspc config focus_follows_pointer     true ## this lets the cursor focus a window

bspc rule -a Emacs state=tiled

sxhkd &
mpd &
picom &
dunst &
xset r rate 300 50 &
unclutter &
polybar bar &
#/home/goku/code/bash/bg > /dev/null &

feh --bg-scale /home/goku/Pictures/cwall/Arch.jpg 

doas /dev/sda3 ~/Downloads

pidof -s runit &&
	! pidof -s pulseaudio >/dev/null 2>&1 &&
	setsid -f pulseaudio --start --exit-idle-time=-1 >/dev/null 2>&1

emacs --daemon &
